###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
# Set programs that you use
$terminal = alacritty
$fileManager = thunar
$menu = walker
$browser = zen-browser
$colorPicker = hyprpicker -a -f hex
