##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Terminal scratchpad
workspace = special:terminal, on-created-empty:[float; center; size 800 600] alacritty -o "font.size=14.0", persistent:false

# Windows from the IntroToQML project in QtCreator float
windowrule {
  name = qtcreator-child-float
  float = on
  match:class = ^(IntroToQML)$
}

# Thunar renaming windows float
windowrule {
    name = thunar-rename-float
    float = on
    center = true
    size = (monitor_w*0.15) (monitor_h*0.1)
    match:class = ^(thunar)$
    match:title = ^(.*Rename.*)$
}

# Default Window Rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-2
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-3
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

